# Generated by Django 5.1.3 on 2024-11-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_venuebooking_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="venue_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_venue",
                to="resources.equipment",
            ),
        ),
    ]
