# Generated by Django 5.1.3 on 2024-11-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_alter_venue_venue_equipment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="venue_equipment",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
    ]
