# Generated by Django 5.1.3 on 2024-11-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_remove_venue_venue_equipment_delete_equipment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="venuebooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
